### ISSUE TITLE
Low speed for shared camera intrinsic optimization in bundle adjustment

### ISSUE THREAD

**Issue by llcc343** [hjwdzh/DeepLM#2]
Hi, I have implemented a new loss function in bundle adjustment to solve the shared camera intrinsic optimization. But I found when all images share the same camera, the optimization speed is about 20 times slower than the case that each image has an camera to be optimized.

**Comment by hjwdzh** [comment]
Thank you for bring this issue up. When it refers to shared intrinsics, the problem is not sparse anymore and the slow performance is expected.

Our solution is to optimize intrinsics and other extrinsics alternatively, which proves to work effectively. For sparse extrinsics, our solver is used. For dense intrinsics, you will only need an Eigen solver:)

**Comment by reynoldscem** [comment]
> Thank you for bring this issue up. When it refers to shared intrinsics, the problem is not sparse anymore and the slow performance is expected.
> 
> 
> 
> Our solution is to optimize intrinsics and other extrinsics alternatively, which proves to work effectively. For sparse extrinsics, our solver is used. For dense intrinsics, you will only need an Eigen solver:)

@hjwdzh do you have an example of this? I'm unsure exactly of what you mean. You do alternative steps of your solver and another where in yours intrinsics are free / unshared and in the other they're constrained / shared?
