### ISSUE TITLE
How to handle large scale bundle adjustment datasets?

### ISSUE THREAD

**Issue by llcc343** [hjwdzh/DeepLM#5]
Hi, the open source code seems not include stochastic domain decomposition in bundle adjustment.  I have tested deeplm on 1dsfm datasets, I noticed that current version can only handle less than 50w projections optimization on rtx 2080 gpu. And current version can not fix first image poses when optimize all image poses like ceres solver.

**Comment by hjwdzh** [comment]
> stochastic domain decomposition
Unfortunately, that is part of the core feature owned by huawei and is not permitted to release.

> 500k projections
It depends on your residual function. The memory is bounded by Nk, where N is the number of residuals and k is the number of variables in each residual function.

> cannot fix image poses
You actually can do it by designing your own residual function.

The idea is to put the first image into the 'constants' argument rather than the 'variables'. For example:
def residual(points_variables, cameras, projections, mask, points_constant):
  points = points_variables * mask + points_constant * (1 - mask)
  proj_residual(points, cameras, projections)

treat projections, points_constant, and mask as constants, set the first row of mask to be zero and others to be one.

**Comment by oliver-batchelor** [comment]
@hjwdzh Curious if you had success here, and if so is there an example anywhere?
